// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: canine_chain/rns/tx.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Coin } from "../../cosmos/base/v1beta1/coin";

export const protobufPackage = "canine_chain.rns";

/** Deprecated! Use MsgRegisterName instead */
export interface MsgRegister {
  creator: string;
  name: string;
  years: number;
  data: string;
}

export interface MsgRegisterResponse {
}

export interface MsgRegisterName {
  creator: string;
  name: string;
  years: number;
  data: string;
  setPrimary: boolean;
}

export interface MsgRegisterNameResponse {
}

export interface MsgUpdate {
  creator: string;
  name: string;
  data: string;
}

export interface MsgUpdateResponse {
}

export interface MsgMakePrimary {
  creator: string;
  name: string;
}

export interface MsgMakePrimaryResponse {
}

export interface MsgBid {
  creator: string;
  name: string;
  bid: Coin | undefined;
}

export interface MsgBidResponse {
}

export interface MsgAcceptBid {
  creator: string;
  name: string;
  from: string;
}

export interface MsgAcceptBidResponse {
}

export interface MsgCancelBid {
  creator: string;
  name: string;
}

export interface MsgCancelBidResponse {
}

export interface MsgList {
  creator: string;
  name: string;
  price: Coin | undefined;
}

export interface MsgListResponse {
}

export interface MsgBuy {
  creator: string;
  name: string;
}

export interface MsgBuyResponse {
}

export interface MsgDelist {
  creator: string;
  name: string;
}

export interface MsgDelistResponse {
}

export interface MsgTransfer {
  creator: string;
  name: string;
  receiver: string;
}

export interface MsgTransferResponse {
}

export interface MsgAddRecord {
  creator: string;
  name: string;
  value: string;
  data: string;
  record: string;
}

export interface MsgAddRecordResponse {
}

export interface MsgDelRecord {
  creator: string;
  name: string;
}

export interface MsgDelRecordResponse {
}

export interface MsgInit {
  creator: string;
}

export interface MsgInitResponse {
}

function createBaseMsgRegister(): MsgRegister {
  return { creator: "", name: "", years: 0, data: "" };
}

export const MsgRegister = {
  encode(message: MsgRegister, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.years !== 0) {
      writer.uint32(24).int64(message.years);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgRegister {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegister();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.years = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegister {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
      years: isSet(object.years) ? gt.Number(object.years) : 0,
      data: isSet(object.data) ? gt.String(object.data) : "",
    };
  },

  toJSON(message: MsgRegister): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.years !== 0) {
      obj.years = Math.round(message.years);
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegister>, I>>(base?: I): MsgRegister {
    return MsgRegister.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegister>, I>>(object: I): MsgRegister {
    const message = createBaseMsgRegister();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    message.years = object.years ?? 0;
    message.data = object.data ?? "";
    return message;
  },
};

function createBaseMsgRegisterResponse(): MsgRegisterResponse {
  return {};
}

export const MsgRegisterResponse = {
  encode(_: MsgRegisterResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgRegisterResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgRegisterResponse {
    return {};
  },

  toJSON(_: MsgRegisterResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterResponse>, I>>(base?: I): MsgRegisterResponse {
    return MsgRegisterResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterResponse>, I>>(_: I): MsgRegisterResponse {
    const message = createBaseMsgRegisterResponse();
    return message;
  },
};

function createBaseMsgRegisterName(): MsgRegisterName {
  return { creator: "", name: "", years: 0, data: "", setPrimary: false };
}

export const MsgRegisterName = {
  encode(message: MsgRegisterName, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.years !== 0) {
      writer.uint32(24).int64(message.years);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.setPrimary !== false) {
      writer.uint32(40).bool(message.setPrimary);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgRegisterName {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterName();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.years = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.setPrimary = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterName {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
      years: isSet(object.years) ? gt.Number(object.years) : 0,
      data: isSet(object.data) ? gt.String(object.data) : "",
      setPrimary: isSet(object.setPrimary) ? gt.Boolean(object.setPrimary) : false,
    };
  },

  toJSON(message: MsgRegisterName): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.years !== 0) {
      obj.years = Math.round(message.years);
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.setPrimary !== false) {
      obj.setPrimary = message.setPrimary;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterName>, I>>(base?: I): MsgRegisterName {
    return MsgRegisterName.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterName>, I>>(object: I): MsgRegisterName {
    const message = createBaseMsgRegisterName();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    message.years = object.years ?? 0;
    message.data = object.data ?? "";
    message.setPrimary = object.setPrimary ?? false;
    return message;
  },
};

function createBaseMsgRegisterNameResponse(): MsgRegisterNameResponse {
  return {};
}

export const MsgRegisterNameResponse = {
  encode(_: MsgRegisterNameResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgRegisterNameResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterNameResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgRegisterNameResponse {
    return {};
  },

  toJSON(_: MsgRegisterNameResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterNameResponse>, I>>(base?: I): MsgRegisterNameResponse {
    return MsgRegisterNameResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterNameResponse>, I>>(_: I): MsgRegisterNameResponse {
    const message = createBaseMsgRegisterNameResponse();
    return message;
  },
};

function createBaseMsgUpdate(): MsgUpdate {
  return { creator: "", name: "", data: "" };
}

export const MsgUpdate = {
  encode(message: MsgUpdate, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.data !== "") {
      writer.uint32(26).string(message.data);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgUpdate {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.data = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdate {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
      data: isSet(object.data) ? gt.String(object.data) : "",
    };
  },

  toJSON(message: MsgUpdate): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdate>, I>>(base?: I): MsgUpdate {
    return MsgUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdate>, I>>(object: I): MsgUpdate {
    const message = createBaseMsgUpdate();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    message.data = object.data ?? "";
    return message;
  },
};

function createBaseMsgUpdateResponse(): MsgUpdateResponse {
  return {};
}

export const MsgUpdateResponse = {
  encode(_: MsgUpdateResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgUpdateResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateResponse {
    return {};
  },

  toJSON(_: MsgUpdateResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateResponse>, I>>(base?: I): MsgUpdateResponse {
    return MsgUpdateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateResponse>, I>>(_: I): MsgUpdateResponse {
    const message = createBaseMsgUpdateResponse();
    return message;
  },
};

function createBaseMsgMakePrimary(): MsgMakePrimary {
  return { creator: "", name: "" };
}

export const MsgMakePrimary = {
  encode(message: MsgMakePrimary, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgMakePrimary {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMakePrimary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgMakePrimary {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
    };
  },

  toJSON(message: MsgMakePrimary): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMakePrimary>, I>>(base?: I): MsgMakePrimary {
    return MsgMakePrimary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMakePrimary>, I>>(object: I): MsgMakePrimary {
    const message = createBaseMsgMakePrimary();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseMsgMakePrimaryResponse(): MsgMakePrimaryResponse {
  return {};
}

export const MsgMakePrimaryResponse = {
  encode(_: MsgMakePrimaryResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgMakePrimaryResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMakePrimaryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgMakePrimaryResponse {
    return {};
  },

  toJSON(_: MsgMakePrimaryResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMakePrimaryResponse>, I>>(base?: I): MsgMakePrimaryResponse {
    return MsgMakePrimaryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMakePrimaryResponse>, I>>(_: I): MsgMakePrimaryResponse {
    const message = createBaseMsgMakePrimaryResponse();
    return message;
  },
};

function createBaseMsgBid(): MsgBid {
  return { creator: "", name: "", bid: undefined };
}

export const MsgBid = {
  encode(message: MsgBid, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.bid !== undefined) {
      Coin.encode(message.bid, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgBid {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgBid();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.bid = Coin.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgBid {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
      bid: isSet(object.bid) ? Coin.fromJSON(object.bid) : undefined,
    };
  },

  toJSON(message: MsgBid): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.bid !== undefined) {
      obj.bid = Coin.toJSON(message.bid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBid>, I>>(base?: I): MsgBid {
    return MsgBid.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBid>, I>>(object: I): MsgBid {
    const message = createBaseMsgBid();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    message.bid = (object.bid !== undefined && object.bid !== null) ? Coin.fromPartial(object.bid) : undefined;
    return message;
  },
};

function createBaseMsgBidResponse(): MsgBidResponse {
  return {};
}

export const MsgBidResponse = {
  encode(_: MsgBidResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgBidResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgBidResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgBidResponse {
    return {};
  },

  toJSON(_: MsgBidResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBidResponse>, I>>(base?: I): MsgBidResponse {
    return MsgBidResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBidResponse>, I>>(_: I): MsgBidResponse {
    const message = createBaseMsgBidResponse();
    return message;
  },
};

function createBaseMsgAcceptBid(): MsgAcceptBid {
  return { creator: "", name: "", from: "" };
}

export const MsgAcceptBid = {
  encode(message: MsgAcceptBid, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.from !== "") {
      writer.uint32(26).string(message.from);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgAcceptBid {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAcceptBid();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.from = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAcceptBid {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
      from: isSet(object.from) ? gt.String(object.from) : "",
    };
  },

  toJSON(message: MsgAcceptBid): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.from !== "") {
      obj.from = message.from;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAcceptBid>, I>>(base?: I): MsgAcceptBid {
    return MsgAcceptBid.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAcceptBid>, I>>(object: I): MsgAcceptBid {
    const message = createBaseMsgAcceptBid();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    message.from = object.from ?? "";
    return message;
  },
};

function createBaseMsgAcceptBidResponse(): MsgAcceptBidResponse {
  return {};
}

export const MsgAcceptBidResponse = {
  encode(_: MsgAcceptBidResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgAcceptBidResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAcceptBidResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgAcceptBidResponse {
    return {};
  },

  toJSON(_: MsgAcceptBidResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAcceptBidResponse>, I>>(base?: I): MsgAcceptBidResponse {
    return MsgAcceptBidResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAcceptBidResponse>, I>>(_: I): MsgAcceptBidResponse {
    const message = createBaseMsgAcceptBidResponse();
    return message;
  },
};

function createBaseMsgCancelBid(): MsgCancelBid {
  return { creator: "", name: "" };
}

export const MsgCancelBid = {
  encode(message: MsgCancelBid, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgCancelBid {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCancelBid();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCancelBid {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
    };
  },

  toJSON(message: MsgCancelBid): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCancelBid>, I>>(base?: I): MsgCancelBid {
    return MsgCancelBid.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCancelBid>, I>>(object: I): MsgCancelBid {
    const message = createBaseMsgCancelBid();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseMsgCancelBidResponse(): MsgCancelBidResponse {
  return {};
}

export const MsgCancelBidResponse = {
  encode(_: MsgCancelBidResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgCancelBidResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCancelBidResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCancelBidResponse {
    return {};
  },

  toJSON(_: MsgCancelBidResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCancelBidResponse>, I>>(base?: I): MsgCancelBidResponse {
    return MsgCancelBidResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCancelBidResponse>, I>>(_: I): MsgCancelBidResponse {
    const message = createBaseMsgCancelBidResponse();
    return message;
  },
};

function createBaseMsgList(): MsgList {
  return { creator: "", name: "", price: undefined };
}

export const MsgList = {
  encode(message: MsgList, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.price !== undefined) {
      Coin.encode(message.price, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgList {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.price = Coin.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgList {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
      price: isSet(object.price) ? Coin.fromJSON(object.price) : undefined,
    };
  },

  toJSON(message: MsgList): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.price !== undefined) {
      obj.price = Coin.toJSON(message.price);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgList>, I>>(base?: I): MsgList {
    return MsgList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgList>, I>>(object: I): MsgList {
    const message = createBaseMsgList();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    message.price = (object.price !== undefined && object.price !== null) ? Coin.fromPartial(object.price) : undefined;
    return message;
  },
};

function createBaseMsgListResponse(): MsgListResponse {
  return {};
}

export const MsgListResponse = {
  encode(_: MsgListResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgListResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgListResponse {
    return {};
  },

  toJSON(_: MsgListResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgListResponse>, I>>(base?: I): MsgListResponse {
    return MsgListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgListResponse>, I>>(_: I): MsgListResponse {
    const message = createBaseMsgListResponse();
    return message;
  },
};

function createBaseMsgBuy(): MsgBuy {
  return { creator: "", name: "" };
}

export const MsgBuy = {
  encode(message: MsgBuy, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgBuy {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgBuy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgBuy {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
    };
  },

  toJSON(message: MsgBuy): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBuy>, I>>(base?: I): MsgBuy {
    return MsgBuy.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBuy>, I>>(object: I): MsgBuy {
    const message = createBaseMsgBuy();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseMsgBuyResponse(): MsgBuyResponse {
  return {};
}

export const MsgBuyResponse = {
  encode(_: MsgBuyResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgBuyResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgBuyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgBuyResponse {
    return {};
  },

  toJSON(_: MsgBuyResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBuyResponse>, I>>(base?: I): MsgBuyResponse {
    return MsgBuyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBuyResponse>, I>>(_: I): MsgBuyResponse {
    const message = createBaseMsgBuyResponse();
    return message;
  },
};

function createBaseMsgDelist(): MsgDelist {
  return { creator: "", name: "" };
}

export const MsgDelist = {
  encode(message: MsgDelist, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgDelist {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDelist();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgDelist {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
    };
  },

  toJSON(message: MsgDelist): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDelist>, I>>(base?: I): MsgDelist {
    return MsgDelist.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDelist>, I>>(object: I): MsgDelist {
    const message = createBaseMsgDelist();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseMsgDelistResponse(): MsgDelistResponse {
  return {};
}

export const MsgDelistResponse = {
  encode(_: MsgDelistResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgDelistResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDelistResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgDelistResponse {
    return {};
  },

  toJSON(_: MsgDelistResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDelistResponse>, I>>(base?: I): MsgDelistResponse {
    return MsgDelistResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDelistResponse>, I>>(_: I): MsgDelistResponse {
    const message = createBaseMsgDelistResponse();
    return message;
  },
};

function createBaseMsgTransfer(): MsgTransfer {
  return { creator: "", name: "", receiver: "" };
}

export const MsgTransfer = {
  encode(message: MsgTransfer, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.receiver !== "") {
      writer.uint32(26).string(message.receiver);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgTransfer {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgTransfer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.receiver = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgTransfer {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
      receiver: isSet(object.receiver) ? gt.String(object.receiver) : "",
    };
  },

  toJSON(message: MsgTransfer): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.receiver !== "") {
      obj.receiver = message.receiver;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgTransfer>, I>>(base?: I): MsgTransfer {
    return MsgTransfer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgTransfer>, I>>(object: I): MsgTransfer {
    const message = createBaseMsgTransfer();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    message.receiver = object.receiver ?? "";
    return message;
  },
};

function createBaseMsgTransferResponse(): MsgTransferResponse {
  return {};
}

export const MsgTransferResponse = {
  encode(_: MsgTransferResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgTransferResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgTransferResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgTransferResponse {
    return {};
  },

  toJSON(_: MsgTransferResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgTransferResponse>, I>>(base?: I): MsgTransferResponse {
    return MsgTransferResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgTransferResponse>, I>>(_: I): MsgTransferResponse {
    const message = createBaseMsgTransferResponse();
    return message;
  },
};

function createBaseMsgAddRecord(): MsgAddRecord {
  return { creator: "", name: "", value: "", data: "", record: "" };
}

export const MsgAddRecord = {
  encode(message: MsgAddRecord, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.value !== "") {
      writer.uint32(26).string(message.value);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.record !== "") {
      writer.uint32(42).string(message.record);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgAddRecord {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAddRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.value = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.record = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAddRecord {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
      value: isSet(object.value) ? gt.String(object.value) : "",
      data: isSet(object.data) ? gt.String(object.data) : "",
      record: isSet(object.record) ? gt.String(object.record) : "",
    };
  },

  toJSON(message: MsgAddRecord): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.record !== "") {
      obj.record = message.record;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAddRecord>, I>>(base?: I): MsgAddRecord {
    return MsgAddRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddRecord>, I>>(object: I): MsgAddRecord {
    const message = createBaseMsgAddRecord();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    message.value = object.value ?? "";
    message.data = object.data ?? "";
    message.record = object.record ?? "";
    return message;
  },
};

function createBaseMsgAddRecordResponse(): MsgAddRecordResponse {
  return {};
}

export const MsgAddRecordResponse = {
  encode(_: MsgAddRecordResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgAddRecordResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAddRecordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgAddRecordResponse {
    return {};
  },

  toJSON(_: MsgAddRecordResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAddRecordResponse>, I>>(base?: I): MsgAddRecordResponse {
    return MsgAddRecordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddRecordResponse>, I>>(_: I): MsgAddRecordResponse {
    const message = createBaseMsgAddRecordResponse();
    return message;
  },
};

function createBaseMsgDelRecord(): MsgDelRecord {
  return { creator: "", name: "" };
}

export const MsgDelRecord = {
  encode(message: MsgDelRecord, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgDelRecord {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDelRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgDelRecord {
    return {
      creator: isSet(object.creator) ? gt.String(object.creator) : "",
      name: isSet(object.name) ? gt.String(object.name) : "",
    };
  },

  toJSON(message: MsgDelRecord): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDelRecord>, I>>(base?: I): MsgDelRecord {
    return MsgDelRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDelRecord>, I>>(object: I): MsgDelRecord {
    const message = createBaseMsgDelRecord();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseMsgDelRecordResponse(): MsgDelRecordResponse {
  return {};
}

export const MsgDelRecordResponse = {
  encode(_: MsgDelRecordResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgDelRecordResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDelRecordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgDelRecordResponse {
    return {};
  },

  toJSON(_: MsgDelRecordResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDelRecordResponse>, I>>(base?: I): MsgDelRecordResponse {
    return MsgDelRecordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDelRecordResponse>, I>>(_: I): MsgDelRecordResponse {
    const message = createBaseMsgDelRecordResponse();
    return message;
  },
};

function createBaseMsgInit(): MsgInit {
  return { creator: "" };
}

export const MsgInit = {
  encode(message: MsgInit, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgInit {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgInit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgInit {
    return { creator: isSet(object.creator) ? gt.String(object.creator) : "" };
  },

  toJSON(message: MsgInit): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgInit>, I>>(base?: I): MsgInit {
    return MsgInit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgInit>, I>>(object: I): MsgInit {
    const message = createBaseMsgInit();
    message.creator = object.creator ?? "";
    return message;
  },
};

function createBaseMsgInitResponse(): MsgInitResponse {
  return {};
}

export const MsgInitResponse = {
  encode(_: MsgInitResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgInitResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgInitResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgInitResponse {
    return {};
  },

  toJSON(_: MsgInitResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgInitResponse>, I>>(base?: I): MsgInitResponse {
    return MsgInitResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgInitResponse>, I>>(_: I): MsgInitResponse {
    const message = createBaseMsgInitResponse();
    return message;
  },
};

export interface Msg {
  Register(request: MsgRegister): Promise<MsgRegisterResponse>;
  RegisterName(request: MsgRegisterName): Promise<MsgRegisterNameResponse>;
  Bid(request: MsgBid): Promise<MsgBidResponse>;
  AcceptBid(request: MsgAcceptBid): Promise<MsgAcceptBidResponse>;
  CancelBid(request: MsgCancelBid): Promise<MsgCancelBidResponse>;
  List(request: MsgList): Promise<MsgListResponse>;
  Buy(request: MsgBuy): Promise<MsgBuyResponse>;
  Delist(request: MsgDelist): Promise<MsgDelistResponse>;
  Transfer(request: MsgTransfer): Promise<MsgTransferResponse>;
  AddRecord(request: MsgAddRecord): Promise<MsgAddRecordResponse>;
  DelRecord(request: MsgDelRecord): Promise<MsgDelRecordResponse>;
  Init(request: MsgInit): Promise<MsgInitResponse>;
  Update(request: MsgUpdate): Promise<MsgUpdateResponse>;
  MakePrimary(request: MsgMakePrimary): Promise<MsgMakePrimaryResponse>;
}

export const MsgServiceName = "canine_chain.rns.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.Register = this.Register.bind(this);
    this.RegisterName = this.RegisterName.bind(this);
    this.Bid = this.Bid.bind(this);
    this.AcceptBid = this.AcceptBid.bind(this);
    this.CancelBid = this.CancelBid.bind(this);
    this.List = this.List.bind(this);
    this.Buy = this.Buy.bind(this);
    this.Delist = this.Delist.bind(this);
    this.Transfer = this.Transfer.bind(this);
    this.AddRecord = this.AddRecord.bind(this);
    this.DelRecord = this.DelRecord.bind(this);
    this.Init = this.Init.bind(this);
    this.Update = this.Update.bind(this);
    this.MakePrimary = this.MakePrimary.bind(this);
  }
  Register(request: MsgRegister): Promise<MsgRegisterResponse> {
    const data = MsgRegister.encode(request).finish();
    const promise = this.rpc.request(this.service, "Register", data);
    return promise.then((data) => MsgRegisterResponse.decode(_m0.Reader.create(data)));
  }

  RegisterName(request: MsgRegisterName): Promise<MsgRegisterNameResponse> {
    const data = MsgRegisterName.encode(request).finish();
    const promise = this.rpc.request(this.service, "RegisterName", data);
    return promise.then((data) => MsgRegisterNameResponse.decode(_m0.Reader.create(data)));
  }

  Bid(request: MsgBid): Promise<MsgBidResponse> {
    const data = MsgBid.encode(request).finish();
    const promise = this.rpc.request(this.service, "Bid", data);
    return promise.then((data) => MsgBidResponse.decode(_m0.Reader.create(data)));
  }

  AcceptBid(request: MsgAcceptBid): Promise<MsgAcceptBidResponse> {
    const data = MsgAcceptBid.encode(request).finish();
    const promise = this.rpc.request(this.service, "AcceptBid", data);
    return promise.then((data) => MsgAcceptBidResponse.decode(_m0.Reader.create(data)));
  }

  CancelBid(request: MsgCancelBid): Promise<MsgCancelBidResponse> {
    const data = MsgCancelBid.encode(request).finish();
    const promise = this.rpc.request(this.service, "CancelBid", data);
    return promise.then((data) => MsgCancelBidResponse.decode(_m0.Reader.create(data)));
  }

  List(request: MsgList): Promise<MsgListResponse> {
    const data = MsgList.encode(request).finish();
    const promise = this.rpc.request(this.service, "List", data);
    return promise.then((data) => MsgListResponse.decode(_m0.Reader.create(data)));
  }

  Buy(request: MsgBuy): Promise<MsgBuyResponse> {
    const data = MsgBuy.encode(request).finish();
    const promise = this.rpc.request(this.service, "Buy", data);
    return promise.then((data) => MsgBuyResponse.decode(_m0.Reader.create(data)));
  }

  Delist(request: MsgDelist): Promise<MsgDelistResponse> {
    const data = MsgDelist.encode(request).finish();
    const promise = this.rpc.request(this.service, "Delist", data);
    return promise.then((data) => MsgDelistResponse.decode(_m0.Reader.create(data)));
  }

  Transfer(request: MsgTransfer): Promise<MsgTransferResponse> {
    const data = MsgTransfer.encode(request).finish();
    const promise = this.rpc.request(this.service, "Transfer", data);
    return promise.then((data) => MsgTransferResponse.decode(_m0.Reader.create(data)));
  }

  AddRecord(request: MsgAddRecord): Promise<MsgAddRecordResponse> {
    const data = MsgAddRecord.encode(request).finish();
    const promise = this.rpc.request(this.service, "AddRecord", data);
    return promise.then((data) => MsgAddRecordResponse.decode(_m0.Reader.create(data)));
  }

  DelRecord(request: MsgDelRecord): Promise<MsgDelRecordResponse> {
    const data = MsgDelRecord.encode(request).finish();
    const promise = this.rpc.request(this.service, "DelRecord", data);
    return promise.then((data) => MsgDelRecordResponse.decode(_m0.Reader.create(data)));
  }

  Init(request: MsgInit): Promise<MsgInitResponse> {
    const data = MsgInit.encode(request).finish();
    const promise = this.rpc.request(this.service, "Init", data);
    return promise.then((data) => MsgInitResponse.decode(_m0.Reader.create(data)));
  }

  Update(request: MsgUpdate): Promise<MsgUpdateResponse> {
    const data = MsgUpdate.encode(request).finish();
    const promise = this.rpc.request(this.service, "Update", data);
    return promise.then((data) => MsgUpdateResponse.decode(_m0.Reader.create(data)));
  }

  MakePrimary(request: MsgMakePrimary): Promise<MsgMakePrimaryResponse> {
    const data = MsgMakePrimary.encode(request).finish();
    const promise = this.rpc.request(this.service, "MakePrimary", data);
    return promise.then((data) => MsgMakePrimaryResponse.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(gt.Number.MAX_SAFE_INTEGER)) {
    throw new gt.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
