// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: canine_chain/jklmint/params.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "canine_chain.jklmint";

export interface Params {
  mintDenom: string;
  /** default 8 */
  devGrantsRatio: number;
  /** default 80 - this includes the community pool allocation */
  stakerRatio: number;
  /** default 4200000 */
  tokensPerBlock: number;
  /** default 6 */
  mintDecrease: number;
  /** multi-sig */
  storageStipendAddress: string;
  /** default 12 */
  storageProviderRatio: number;
}

function createBaseParams(): Params {
  return {
    mintDenom: "",
    devGrantsRatio: 0,
    stakerRatio: 0,
    tokensPerBlock: 0,
    mintDecrease: 0,
    storageStipendAddress: "",
    storageProviderRatio: 0,
  };
}

export const Params = {
  encode(message: Params, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.mintDenom !== "") {
      writer.uint32(10).string(message.mintDenom);
    }
    if (message.devGrantsRatio !== 0) {
      writer.uint32(16).int64(message.devGrantsRatio);
    }
    if (message.stakerRatio !== 0) {
      writer.uint32(24).int64(message.stakerRatio);
    }
    if (message.tokensPerBlock !== 0) {
      writer.uint32(32).int64(message.tokensPerBlock);
    }
    if (message.mintDecrease !== 0) {
      writer.uint32(40).int64(message.mintDecrease);
    }
    if (message.storageStipendAddress !== "") {
      writer.uint32(50).string(message.storageStipendAddress);
    }
    if (message.storageProviderRatio !== 0) {
      writer.uint32(56).int64(message.storageProviderRatio);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Params {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.mintDenom = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.devGrantsRatio = longToNumber(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.stakerRatio = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.tokensPerBlock = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.mintDecrease = longToNumber(reader.int64() as Long);
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.storageStipendAddress = reader.string();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.storageProviderRatio = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      mintDenom: isSet(object.mintDenom) ? gt.String(object.mintDenom) : "",
      devGrantsRatio: isSet(object.devGrantsRatio) ? gt.Number(object.devGrantsRatio) : 0,
      stakerRatio: isSet(object.stakerRatio) ? gt.Number(object.stakerRatio) : 0,
      tokensPerBlock: isSet(object.tokensPerBlock) ? gt.Number(object.tokensPerBlock) : 0,
      mintDecrease: isSet(object.mintDecrease) ? gt.Number(object.mintDecrease) : 0,
      storageStipendAddress: isSet(object.storageStipendAddress) ? gt.String(object.storageStipendAddress) : "",
      storageProviderRatio: isSet(object.storageProviderRatio) ? gt.Number(object.storageProviderRatio) : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.mintDenom !== "") {
      obj.mintDenom = message.mintDenom;
    }
    if (message.devGrantsRatio !== 0) {
      obj.devGrantsRatio = Math.round(message.devGrantsRatio);
    }
    if (message.stakerRatio !== 0) {
      obj.stakerRatio = Math.round(message.stakerRatio);
    }
    if (message.tokensPerBlock !== 0) {
      obj.tokensPerBlock = Math.round(message.tokensPerBlock);
    }
    if (message.mintDecrease !== 0) {
      obj.mintDecrease = Math.round(message.mintDecrease);
    }
    if (message.storageStipendAddress !== "") {
      obj.storageStipendAddress = message.storageStipendAddress;
    }
    if (message.storageProviderRatio !== 0) {
      obj.storageProviderRatio = Math.round(message.storageProviderRatio);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.mintDenom = object.mintDenom ?? "";
    message.devGrantsRatio = object.devGrantsRatio ?? 0;
    message.stakerRatio = object.stakerRatio ?? 0;
    message.tokensPerBlock = object.tokensPerBlock ?? 0;
    message.mintDecrease = object.mintDecrease ?? 0;
    message.storageStipendAddress = object.storageStipendAddress ?? "";
    message.storageProviderRatio = object.storageProviderRatio ?? 0;
    return message;
  },
};

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(gt.Number.MAX_SAFE_INTEGER)) {
    throw new gt.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
