export { txClient as bankTxClient, queryClient as bankQueryClient } from './protos/bank'
export { txClient as cosmTxClient, queryClient as cosmQueryClient } from './protos/cosmwasm'
export { txClient as dsigTxClient, queryClient as dsigQueryClient } from './protos/dsig'
export { txClient as filetreeTxClient, queryClient as filetreeQueryClient } from './protos/filetree'
export { txClient as govTxClient, queryClient as govQueryClient } from './protos/governance'
export { txClient as jklAccountsTxClient, queryClient as jklAccountsQueryClient } from './protos/jklaccounts'
export { txClient as jklMintTxClient, queryClient as jklMintQueryClient } from './protos/jklmint'
export { txClient as lpTxClient, queryClient as lpQueryClient } from './protos/lp'
export { txClient as rnsTxClient, queryClient as rnsQueryClient } from './protos/rns'
export { txClient as stakingTxClient, queryClient as stakingQueryClient } from './protos/staking'
export { txClient as storageTxClient, queryClient as storageQueryClient } from './protos/storage'

export { Api as bankQueryApi } from './protos/bank/rest'
export { Api as cosmQueryApi } from './protos/cosmwasm/rest'
export { Api as dsigQueryApi } from './protos/dsig/rest'
export { Api as filetreeQueryApi } from './protos/filetree/rest'
export { Api as govQueryApi } from './protos/governance/rest'
export { Api as jklAccountsQueryApi } from './protos/jklaccounts/rest'
export { Api as jklMintQueryApi } from './protos/jklmint/rest'
export { Api as lpQueryApi } from './protos/lp/rest'
export { Api as rnsQueryApi } from './protos/rns/rest'
export { Api as stakingQueryApi } from './protos/staking/rest'
export { Api as storageQueryApi } from './protos/storage/rest'
